[tools]
# Put any tools you want to install here. To install Rojo 7, you'd use:
selene = { source = "Kampfkarren/selene", version = "x" }
rojo = { github = "rojo-rbx/rojo", version = "7.0.0" }
wally = { source = "UpliftGames/wally", version = "0.3.2"}